name: DK-Menu-Plugin
version: '${project.version}'
main: org.example.dmytrok.dkmenuplugin.DK_Menu_Plugin
commands:
  adminMenu:
    description: Admin Menu
    usage: /adminMenu
    permission: adminMenu.admin
  menu:
    description: Menu
    usage: /menu
    permission: menu.user
  personalAccount:
    description: Personal Account
    usage: personalaccount
    permission: personalaccount.user
  backpack:
    description: Backpack
    usage: backpack
    permission: backpack.user
  trademenu:
    description: Trade System
    usage: trademenu
    permission: trademenu.user
permissions:
  adminMenu.admin:
    description: Only admin can open this menu
    default: op
  menu.user:
    description: Menu
    default: not op
  personalAccount.user:
    description: Personal Account
    default: not op
  backpack.user:
    description: backpack
    default: not op
  trademenu.user:
    description: trademenu
    default: not op
