name: DK-Menu-Plugin
version: '1'
main: org.example.dmytrok.dkmenuplugin.DK_Menu_Plugin
commands:
  adminMenu:
    description: Admin Menu
    usage: /adminMenu
    permission: adminMenu.admin
  menu:
    description: Menu
    usage: /menu
    permission: menu.user
  personalAccount:
    description: Personal Account
    usage: personalaccount
    permission: personalaccount.user
permissions:
  adminMenu.admin:
    description: Only admin can open this menu
    default: op
  menu.user:
    description: Menu
  personalAccount.user:
    description: Personal Account
